<div class="col-md-2">
    <a href="<?= $_SERVER['PHP_SELF']; ?>" class="btn btn-default btn-sm btn-block"><span class="glyphicon glyphicon-home"></span> Inicio</a>
    <button class="btn btn-default btn-sm btn-block" data-toggle="modal" data-target="#edit-profile"><span class="glyphicon glyphicon-user"></span> Editar</button>
    <!-- <button class="btn btn-default btn-sm btn-block"><span class="glyphicon glyphicon-cog"></span> Ajustes</button> -->
    <button id="btn-logout" class="btn btn-default btn-sm btn-block"><span class="glyphicon glyphicon-off"></span> Salir</button>
</div>
<div class="col-md-8">
    <span style="font-size: 3rem !important;" class="text-center">Bienvenido: <span id="data-username"></span></span>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo cum doloremque sunt! Quasi corporis eaque ratione possimus laborum repellat non doloribus vero neque magnam aperiam excepturi adipisci dicta, eum sequi dolorum animi. Dicta officiis corrupti unde, dolor veniam reprehenderit natus tempore quaerat, laborum quae, non doloremque nihil quidem dolores culpa ducimus? Corporis dolor, molestiae earum alias commodi repellendus facere minima facilis voluptates at qui eius saepe sequi assumenda dolores libero inventore adipisci deserunt eveniet. Tempora, animi ipsum. Eveniet libero, delectus expedita obcaecati voluptate blanditiis quam vitae. Totam est placeat saepe, consequuntur magni, consectetur reiciendis odit tempore minima voluptates nisi adipisci!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo cum doloremque sunt! Quasi corporis eaque ratione possimus laborum repellat non doloribus vero neque magnam aperiam excepturi adipisci dicta, eum sequi dolorum animi. Dicta officiis corrupti unde, dolor veniam reprehenderit natus tempore quaerat, laborum quae, non doloremque nihil quidem dolores culpa ducimus? Corporis dolor, molestiae earum alias commodi repellendus facere minima facilis voluptates at qui eius saepe sequi assumenda dolores libero inventore adipisci deserunt eveniet. Tempora, animi ipsum. Eveniet libero, delectus expedita obcaecati voluptate blanditiis quam vitae. Totam est placeat saepe, consequuntur magni, consectetur reiciendis odit tempore minima voluptates nisi adipisci!</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo cum doloremque sunt! Quasi corporis eaque ratione possimus laborum repellat non doloribus vero neque magnam aperiam excepturi adipisci dicta, eum sequi dolorum animi. Dicta officiis corrupti unde, dolor veniam reprehenderit natus tempore quaerat, laborum quae, non doloremque nihil quidem dolores culpa ducimus? Corporis dolor, molestiae earum alias commodi repellendus facere minima facilis voluptates at qui eius saepe sequi assumenda dolores libero inventore adipisci deserunt eveniet. Tempora, animi ipsum. Eveniet libero, delectus expedita obcaecati voluptate blanditiis quam vitae. Totam est placeat saepe, consequuntur magni, consectetur reiciendis odit tempore minima voluptates nisi adipisci!</p>
</div>

<?php include_once 'partials/dashboard/edit-profile.php'; ?>
